apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: demo-blog
data:
  BLOG_TITLE: "This is my second try with the GitOps Blog"
  BLOG_SUBTITLE: "Mes aventures GitOps"
  AUTHOR: "kengreklammen"
  VERSION: "1.0.0"
  THEME: "dark"